/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import AppLogic.*;
import AppLogic.SearchPatient;
import DataBase.DbFacade;
import DataBase.DbPatient;
import javax.swing.JOptionPane;

/**
 *
 * @author Ikhlas
 */
public class SearchPatientScreen extends javax.swing.JFrame {
           
    /**
     * Creates new form SearchPatientScreen
     */
    public SearchPatientScreen() {
        initComponents();
        jPanelViewSearchResult.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldCardNum = new javax.swing.JTextField();
        jButtonSearch = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanelViewSearchResult = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabelFirstName = new javax.swing.JLabel();
        jLabelLastName = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelAge = new javax.swing.JLabel();
        jLabelPhone = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Search for patient");

        jLabel1.setText("Medicare card Number");

        jButtonSearch.setText("Search");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jLabel2.setText("The medicare card Number for a patient like 2017xxxx");

        jLabel3.setForeground(new java.awt.Color(102, 0, 102));
        jLabel3.setText("Name");

        jLabel5.setForeground(new java.awt.Color(102, 0, 102));
        jLabel5.setText("Phone");

        jLabel7.setForeground(new java.awt.Color(102, 0, 102));
        jLabel7.setText("email");

        jLabel8.setForeground(new java.awt.Color(102, 0, 102));
        jLabel8.setText("Age");

        javax.swing.GroupLayout jPanelViewSearchResultLayout = new javax.swing.GroupLayout(jPanelViewSearchResult);
        jPanelViewSearchResult.setLayout(jPanelViewSearchResultLayout);
        jPanelViewSearchResultLayout.setHorizontalGroup(
            jPanelViewSearchResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelViewSearchResultLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanelViewSearchResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addGroup(jPanelViewSearchResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelViewSearchResultLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelViewSearchResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelViewSearchResultLayout.createSequentialGroup()
                                .addGroup(jPanelViewSearchResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanelViewSearchResultLayout.createSequentialGroup()
                                        .addComponent(jLabelFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))
                                    .addGroup(jPanelViewSearchResultLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelPhone)
                                        .addGap(77, 77, 77)))
                                .addGroup(jPanelViewSearchResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelViewSearchResultLayout.createSequentialGroup()
                                        .addGap(123, 123, 123)
                                        .addComponent(jLabelLastName))
                                    .addComponent(jLabelEmail, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(jLabelAge, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelViewSearchResultLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel7)))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        jPanelViewSearchResultLayout.setVerticalGroup(
            jPanelViewSearchResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelViewSearchResultLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanelViewSearchResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelFirstName)
                    .addComponent(jLabelLastName))
                .addGap(18, 18, 18)
                .addGroup(jPanelViewSearchResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabelEmail)
                    .addComponent(jLabel7)
                    .addComponent(jLabelPhone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanelViewSearchResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabelAge))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldCardNum, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(jButtonSearch))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jPanelViewSearchResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldCardNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearch))
                .addGap(33, 33, 33)
                .addComponent(jPanelViewSearchResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 AbstractPatient aPatient;
 AbstractPatient aPatient2;
    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
         try{
            // aPatient = new Patient();
        
            int num =  Integer.parseInt(jTextFieldCardNum.getText());
             //aPatient.setMedicareCardNumber(num);
       
       //  DbFacade.getDbFacade().searchPatient(aPatient);
         
        aPatient2 =  new SearchPatient().getPatient(num);
         result();
         }catch(Exception ex){
             JOptionPane.showMessageDialog(null,ex.getMessage());
         } 
           
    }//GEN-LAST:event_jButtonSearchActionPerformed

    public void result(){
        if(aPatient2 instanceof NullPatient){
           JOptionPane.showMessageDialog(null, aPatient2.getMedicareCardNumber());
        }
        else if(aPatient2 instanceof Patient){
         jLabelPhone.setText(Integer.toString(aPatient2.getPhoneNumber())); 
        jLabelAge.setText((Integer.toString(aPatient2.getAge())));
        jLabelEmail.setText(aPatient2.getEmail());
        jLabelFirstName.setText(aPatient2.getName());
        jPanelViewSearchResult.setVisible(true);
    }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchPatientScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchPatientScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchPatientScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchPatientScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchPatientScreen().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelAge;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelFirstName;
    private javax.swing.JLabel jLabelLastName;
    private javax.swing.JLabel jLabelPhone;
    private javax.swing.JPanel jPanelViewSearchResult;
    private javax.swing.JTextField jTextFieldCardNum;
    // End of variables declaration//GEN-END:variables
}
